#version 450
#extension GL_GOOGLE_include_directive : require
#include "../post_common_vulkan.glsl"

void main() {
    vUV = vec2(gl_GlobalInvocationID.xy) / vec2(imageSize(outputImage));
    vec4 sceneColor = texture(uScene, vUV);
    vec3 pix = pixelateRetro(vUV, 256.0, 64.0);
    vec3 result = mix(sceneColor.rgb, pix, uStrength);
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(result, sceneColor.a));
}
