#version 450
#extension GL_GOOGLE_include_directive : require
#include "../post_common_vulkan.glsl"

void main() {
    vUV = vec2(gl_GlobalInvocationID.xy) / vec2(imageSize(outputImage));
    vec4 sceneColor = texture(uScene, vUV);
    vec2 uv = lensDistort(vUV, uStrength * 1.5);
    vec3 result = texture(uScene, clamp(uv, 0.0, 1.0)).rgb;
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(result, sceneColor.a));
}
